Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,48 +13,62 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel.
 jobs:
-  build:
-    name: Analyze project with Jtest
-    
+  Analyze_project_with_Jtest:
+
     permissions:
       # required for all workflows
       security-events: write
       # only required for workflows in private repositories
       actions: read
       contents: read
-    
+
+      # Specifies the type of runner that the job will run on.
+    runs-on: self-hosted
+  
+    # Steps represent a sequence of tasks that will be executed as part of the job.
+    steps:
+      
+      # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
+      - name: Checkout repository
+        uses: actions/checkout@v3
+      
+      # Generates the jtest.data.json input file.
+      - name: Create input for Jtest
+        run: mvn clean install jtest:jtest "-Djtest.skip=true" 
+  
+      # Runs code analysis with Jtest
+      - name: Run Jtest
+        id: jtest
+        uses: parasoft/run-jtest-action@2.0.0
+        with:
+          #Uses the jtest.data.json generated with the Maven command in the previous step
+          input: target/jtest/jtest.data.json
+
+  Upload_Jtest_report:
+    needs: [Analyze_project_with_Jtest]
+
+    permissions:
+      # required for all workflows
+      security-events: write
+      # only required for workflows in private repositories
+      actions: read
+      contents: read
+
     # Specifies the type of runner that the job will run on.
     runs-on: self-hosted
 
     # Steps represent a sequence of tasks that will be executed as part of the job.
     steps:
+      # Uploads an archive that includes all report files (.xml, .html, .sarif).
+      - name: Archive reports
+        # if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: Static analysis reports
+          path: reports/*.*
     
-    # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
-    - name: Checkout repository
-      uses: actions/checkout@v3
-    
-    # Generates the jtest.data.json input file.
-    - name: Create input for Jtest
-      run: mvn clean install jtest:jtest "-Djtest.skip=true" 
-
-    # Runs code analysis with Jtest
-    - name: Run Jtest
-      id: jtest
-      uses: parasoft/run-jtest-action@2.0.0
-      with:
-        #Uses the jtest.data.json generated with the Maven command in the previous step
-        input: target/jtest/jtest.data.json
-
-    # Uploads an archive that includes all report files (.xml, .html, .sarif).
-    - name: Archive reports
-      if: always()
-      uses: actions/upload-artifact@v3
-      with:
-        name: Static analysis reports
-        path: reports/*.*
-
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v4
-      if: success() || failure() # always run even if the previous step fails
-      with:
-        report_paths: 'reports/unit/coverage.xml'
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        # if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'reports/unit/coverage.xml'
